import { Question, QuizCategory } from './types';

export const QUIZ_CATEGORIES: QuizCategory[] = [
  {
    id: 'intro-ml',
    title: 'Introduction to Machine Learning',
    topic: 'Introduction to Machine Learning',
    shortDescription: 'Test foundational concepts of Supervised, Unsupervised, and Bias-Variance tradeoffs.',
    iconName: 'brain',
    questionCount: 5,
    difficultyDistribution: { easy: 2, medium: 2, hard: 1 },
    playgroundLabRoute: '/playground/linear-lab',
    recommendedLabTitle: 'Linear Regression Playground',
  },
  {
    id: 'linear-regression',
    title: 'Linear Regression',
    topic: 'Linear Regression',
    shortDescription: 'Master OLS Cost Minimization, MSE derivations, Normal Equation & L1/L2 Regularization.',
    iconName: 'line-chart',
    questionCount: 6,
    difficultyDistribution: { easy: 2, medium: 3, hard: 1 },
    playgroundLabRoute: '/playground/linear-lab',
    recommendedLabTitle: 'Linear Regression Laboratory',
  },
  {
    id: 'gradient-descent',
    title: 'Gradient Descent',
    topic: 'Gradient Descent',
    shortDescription: 'Evaluate SGD, Mini-Batch, Learning Rates, Momentum, and Adam Optimization step mechanics.',
    iconName: 'trending-down',
    questionCount: 6,
    difficultyDistribution: { easy: 2, medium: 3, hard: 1 },
    playgroundLabRoute: '/playground/gd-lab',
    recommendedLabTitle: 'Gradient Descent Laboratory',
  },
  {
    id: 'logistic-regression',
    title: 'Logistic Regression',
    topic: 'Logistic Regression',
    shortDescription: 'Assess Sigmoid activation, Log-Loss cost, Binary Decision Boundaries & Precision/Recall.',
    iconName: 'binary',
    questionCount: 6,
    difficultyDistribution: { easy: 2, medium: 3, hard: 1 },
    playgroundLabRoute: '/playground/logistic-lab',
    recommendedLabTitle: 'Logistic Regression Laboratory',
  },
  {
    id: 'decision-trees',
    title: 'Decision Trees',
    topic: 'Decision Trees',
    shortDescription: 'Examine Entropy, Information Gain, Gini Impurity, and Tree Pruning strategies.',
    iconName: 'git-branch',
    questionCount: 5,
    difficultyDistribution: { easy: 2, medium: 2, hard: 1 },
    playgroundLabRoute: '/playground/overfitting-lab',
    recommendedLabTitle: 'Overfitting & Capacity Laboratory',
  },
  {
    id: 'kmeans-clustering',
    title: 'K-Means Clustering',
    topic: 'K-Means Clustering',
    shortDescription: 'Analyze Unsupervised Centroid updates, Inertia WCSS, Elbow Method & Silhouette Scores.',
    iconName: 'layers',
    questionCount: 5,
    difficultyDistribution: { easy: 2, medium: 2, hard: 1 },
    playgroundLabRoute: '/playground/linear-lab',
    recommendedLabTitle: 'Feature Space Playground',
  },
  {
    id: 'pca',
    title: 'Principal Component Analysis (PCA)',
    topic: 'PCA',
    shortDescription: 'Evaluate Variance Maximization, Eigenvectors, Covariance Matrices & Dimensionality Reduction.',
    iconName: 'shrink',
    questionCount: 5,
    difficultyDistribution: { easy: 2, medium: 2, hard: 1 },
    playgroundLabRoute: '/playground/linear-lab',
    recommendedLabTitle: 'Dimensionality & Feature Space Lab',
  },
  {
    id: 'neural-networks',
    title: 'Neural Networks & Deep Learning',
    topic: 'Neural Networks',
    shortDescription: 'Calculate Forward Propagation, Backpropagation Chain Rule, Activations (ReLU, Softmax) & Dropout.',
    iconName: 'network',
    questionCount: 6,
    difficultyDistribution: { easy: 2, medium: 3, hard: 1 },
    playgroundLabRoute: '/playground/nn-lab',
    recommendedLabTitle: 'Neural Network Laboratory',
  },
  {
    id: 'overfitting-underfitting',
    title: 'Overfitting & Underfitting',
    topic: 'Overfitting',
    shortDescription: 'Diagnose High Bias vs High Variance, Learning Curves, Regularization & Early Stopping.',
    iconName: 'shield-alert',
    questionCount: 6,
    difficultyDistribution: { easy: 2, medium: 3, hard: 1 },
    playgroundLabRoute: '/playground/overfitting-lab',
    recommendedLabTitle: 'Overfitting Laboratory',
  },
  {
    id: 'master-case-study',
    title: 'Cumulative Master Case Study',
    topic: 'Cumulative Case Study',
    shortDescription: 'Multi-topic production scenario integration testing real-world ML deployment choices.',
    iconName: 'award',
    questionCount: 3,
    difficultyDistribution: { easy: 1, medium: 1, hard: 1 },
    playgroundLabRoute: '/playground/nn-lab',
    recommendedLabTitle: 'Neural Network & System Lab',
  },
];

export const ALL_QUESTIONS: Question[] = [
  // 1. INTRO TO ML
  {
    id: 'IML-01',
    topic: 'Introduction to Machine Learning',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which of the following problems is best solved using Supervised Learning?',
    options: [
      'Grouping e-commerce customers by purchase history without labels',
      'Predicting house prices based on historical square footage and price labels',
      'Reducing a 100-dimensional dataset down to 2 dimensions for visualization',
      'Finding anomalies in server logs without labeled fraud data',
    ],
    correct_answer: 'Predicting house prices based on historical square footage and price labels',
    explanation: 'Supervised learning requires paired input features (x) and explicit target labels (y) during training.',
    real_time_application: 'Zillow and Redfin use supervised regression models trained on historic sales data to estimate market home values.',
    hint: 'Look for the task that relies on labeled training pairs (x, y).',
    tags: ['Supervised Learning', 'Basics'],
  },
  {
    id: 'IML-02',
    topic: 'Introduction to Machine Learning',
    difficulty: 'easy',
    type: 'true_false',
    question: 'True or False: In Unsupervised Learning, the dataset contains labeled output targets for every sample.',
    options: ['True', 'False'],
    correct_answer: 'False',
    explanation: 'Unsupervised learning algorithms operate exclusively on unlabeled input data (x) to discover hidden structure or patterns.',
    real_time_application: 'Spotify uses unsupervised clustering to group songs into automated user playlists based on audio features without human labeling.',
    hint: 'Think about whether unsupervised algorithms receive ground-truth labels.',
    tags: ['Unsupervised Learning'],
  },
  {
    id: 'IML-03',
    topic: 'Introduction to Machine Learning',
    difficulty: 'medium',
    type: 'mcq',
    question: 'High Variance in a machine learning model is primarily associated with which problem?',
    options: [
      'Underfitting',
      'Overfitting',
      'High Training Error',
      'Zero Model Capacity',
    ],
    correct_answer: 'Overfitting',
    explanation: 'High Variance means the model captures noise in the training set, performing exceptionally well on train data but failing to generalize to unseen test data (Overfitting).',
    real_time_application: 'Overfit algorithmic trading models fail dramatically when deployed to live markets because they memorize historical noise.',
    hint: 'High variance means the model changes drastically with small training data shifts.',
    tags: ['Bias-Variance', 'Overfitting'],
  },
  {
    id: 'IML-04',
    topic: 'Introduction to Machine Learning',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'A healthcare startup builds a diagnostic model. Training accuracy is 99.8%, but accuracy on new patient test scans drops to 62.1%.',
    question: 'What is the primary cause of this performance drop and what is the best initial fix?',
    options: [
      'Underfitting; increase model complexity',
      'Overfitting; apply regularization or gather more diverse training data',
      'High Bias; remove feature normalization',
      'Data leakage; remove validation split',
    ],
    correct_answer: 'Overfitting; apply regularization or gather more diverse training data',
    explanation: 'A huge gap between 99.8% train accuracy and 62.1% test accuracy indicates severe overfitting (High Variance). Regularization or data augmentation restores generalization.',
    real_time_application: 'FDA-approved AI medical imaging tools enforce strict L2 regularization to prevent memorizing patient scan artifacts.',
    hint: 'Analyze the gap between training and validation accuracy.',
    tags: ['Healthcare ML', 'Diagnostics'],
  },
  {
    id: 'IML-05',
    topic: 'Introduction to Machine Learning',
    difficulty: 'hard',
    type: 'formula_id',
    question: 'Which equation correctly expresses the decomposition of Expected Test Error?',
    formula: '\\text{Expected Error} = \\text{Bias}^2 + \\text{Variance} + \\sigma^2',
    options: [
      'Expected Error = Bias^2 + Variance + Irreducible Noise',
      'Expected Error = Bias + Variance^2 + Learning Rate',
      'Expected Error = Loss / (Bias * Variance)',
      'Expected Error = Total Epochs - Learning Rate',
    ],
    correct_answer: 'Expected Error = Bias^2 + Variance + Irreducible Noise',
    explanation: 'Total expected generalization error decomposes into squared Bias (underfitting), Variance (overfitting), and irreducible noise (sigma^2).',
    real_time_application: 'ML System Engineers tune model capacity to strike the optimal minimum at the Bias-Variance curve intersection.',
    hint: 'Irreducible noise represents data measurement error that cannot be eliminated by any model.',
    tags: ['Decomposition', 'Math'],
  },

  // 2. LINEAR REGRESSION
  {
    id: 'LR-01',
    topic: 'Linear Regression',
    difficulty: 'easy',
    type: 'mcq',
    question: 'In the simple linear regression formula ŷ = wx + b, what does the parameter w represent?',
    formula: '\\hat{y} = w x + b',
    options: [
      'The y-intercept when x = 0',
      'The slope (rate of change of y with respect to x)',
      'The mean squared error loss',
      'The regularizer weight decay factor',
    ],
    correct_answer: 'The slope (rate of change of y with respect to x)',
    explanation: 'The weight w measures the slope, indicating how many units ŷ changes for every 1-unit increase in feature x.',
    real_time_application: 'In salary prediction, w represents the dollar increase in salary per additional year of experience.',
    hint: 'Recall rise over run (Δy / Δx).',
    tags: ['Linear Regression', 'Slope'],
  },
  {
    id: 'LR-02',
    topic: 'Linear Regression',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'The vertical distance between an actual data point y_i and predicted point ŷ_i is called a ______.',
    options: [
      'Residual',
      'Gradient',
      'Hyperparameter',
      'Centroid',
    ],
    correct_answer: 'Residual',
    explanation: 'The residual e_i = y_i - ŷ_i is the error for individual point i.',
    real_time_application: 'Residual analysis plots are used by quantitative analysts to check for heteroscedasticity in financial time-series.',
    hint: 'It represents individual prediction error per sample.',
    tags: ['Residuals', 'Loss'],
  },
  {
    id: 'LR-03',
    topic: 'Linear Regression',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Given actual targets Y = [3, 5] and model predictions Ŷ = [2, 7], calculate the Mean Squared Error (MSE).',
    formula: 'MSE = \\frac{1}{n} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2',
    options: ['1.5', '2.5', '5.0', '10.0'],
    correct_answer: '2.5',
    explanation: 'Residual 1: (3 - 2)^2 = 1. Residual 2: (5 - 7)^2 = 4. Sum = 5. Average over n=2: 5 / 2 = 2.5.',
    real_time_application: 'MSE is the standard metric used in energy demand forecasting to penalize large prediction mistakes.',
    hint: 'Square each difference (3-2) and (5-7), add them, and divide by 2.',
    tags: ['Numerical', 'MSE Calculation'],
  },
  {
    id: 'LR-04',
    topic: 'Linear Regression',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'You add L1 (Lasso) regularization to a linear regression model trained on 100 correlated features.',
    question: 'What unique property will L1 regularization display compared to L2 (Ridge) regularization?',
    options: [
      'L1 shrinks feature weights smoothly near zero without making them exactly 0',
      'L1 forces insignificant feature weights to become exactly 0, performing automatic feature selection',
      'L1 increases model training time by exponentiating weights',
      'L1 makes the cost function non-convex with multiple local minima',
    ],
    correct_answer: 'L1 forces insignificant feature weights to become exactly 0, performing automatic feature selection',
    explanation: 'L1 regularization uses an absolute value penalty (|w|), producing sparse weight vectors where useless feature weights drop to zero.',
    real_time_application: 'Genomics researchers use Lasso regression to select the top 20 relevant genes out of 20,000 candidate DNA markers.',
    hint: 'L1 penalty creates diamond-shaped constraint boundaries that intersect axes at zero.',
    tags: ['Lasso', 'Regularization'],
  },
  {
    id: 'LR-05',
    topic: 'Linear Regression',
    difficulty: 'hard',
    type: 'formula_id',
    question: 'What is the analytical Normal Equation closed-form solution for optimal parameter vector w*?',
    formula: 'w^* = (X^T X)^{-1} X^T y',
    options: [
      'w* = (X^T X)^(-1) X^T y',
      'w* = X^T X y',
      'w* = (X X^T)^(-1) y',
      'w* = w - alpha * grad(J)',
    ],
    correct_answer: 'w* = (X^T X)^(-1) X^T y',
    explanation: 'Setting the MSE partial derivatives to zero yields w* = (X^T X)^(-1) X^T y, finding the global optimum directly without gradient descent iterations.',
    real_time_application: 'Scikit-Learn uses SVD or Normal Equation solver when dataset dimensions fit easily in RAM.',
    hint: 'Involves inverting the Gram matrix X^T X.',
    tags: ['Normal Equation', 'Closed-Form'],
  },

  // 3. GRADIENT DESCENT
  {
    id: 'GD-01',
    topic: 'Gradient Descent',
    difficulty: 'easy',
    type: 'mcq',
    question: 'In parameter update rule w^(t+1) = w^(t) - α (∂J/∂w), what does the hyperparameter α represent?',
    formula: 'w^{(t+1)} = w^{(t)} - \\alpha \\frac{\\partial J}{\\partial w}',
    options: [
      'Momentum Decay Rate',
      'Learning Rate (Step Size)',
      'Batch Size',
      'L2 Weight Penalty',
    ],
    correct_answer: 'Learning Rate (Step Size)',
    explanation: 'The learning rate α scales how far parameter w steps in the opposite direction of the loss gradient.',
    real_time_application: 'Selecting α = 0.001 is common in PyTorch Adam optimizers for training computer vision models.',
    hint: 'Controls downhill step distance per iteration.',
    tags: ['Gradient Descent', 'Learning Rate'],
  },
  {
    id: 'GD-02',
    topic: 'Gradient Descent',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What symptom indicates that your Learning Rate (α) is set too high during gradient descent training?',
    options: [
      'Loss decreases monotonically and slowly takes 10,000 epochs to converge',
      'Loss oscillates wildly or increases to infinity (divergence)',
      'Gradients drop to zero on epoch 1',
      'The slope w stops changing completely',
    ],
    correct_answer: 'Loss oscillates wildly or increases to infinity (divergence)',
    explanation: 'Excessively large α causes optimization steps to overshoot the local minimum, bouncing up opposite walls of the loss landscape.',
    real_time_application: 'Divergence causes NaN (Not a Number) loss errors in deep learning pipelines during training.',
    hint: 'Think about stepping over the valley bottom to a higher position on the opposite side.',
    tags: ['Overshooting', 'Divergence'],
  },
  {
    id: 'GD-03',
    topic: 'Gradient Descent',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'You are training a model on 1,000,000 data points. Full Batch Gradient Descent takes 45 minutes per epoch.',
    question: 'Which variant of Gradient Descent updates parameters after evaluating a small batch of 64 or 128 samples?',
    options: [
      'Stochastic Gradient Descent (Single sample)',
      'Mini-Batch Gradient Descent',
      'Newton-Raphson Second-Order Descent',
      'Full Batch Normal Descent',
    ],
    correct_answer: 'Mini-Batch Gradient Descent',
    explanation: 'Mini-Batch GD combines speed and GPU parallelism by computing gradient estimates over subsets (e.g. 64 or 128 samples).',
    real_time_application: 'All modern deep neural networks (LLMs, ResNets) train using Mini-Batch GD for GPU efficiency.',
    hint: 'It operates on sub-batches of the dataset.',
    tags: ['Mini-Batch', 'Optimization'],
  },
  {
    id: 'GD-04',
    topic: 'Gradient Descent',
    difficulty: 'hard',
    type: 'mcq',
    question: 'Given w = 2.0, gradient ∂J/∂w = 4.0, and learning rate α = 0.05, calculate the updated weight w^(t+1).',
    formula: 'w^{(t+1)} = w^{(t)} - \\alpha \\frac{\\partial J}{\\partial w}',
    options: ['2.20', '1.80', '1.95', '2.05'],
    correct_answer: '1.80',
    explanation: 'w^(t+1) = 2.0 - (0.05 * 4.0) = 2.0 - 0.20 = 1.80.',
    real_time_application: 'Deep learning frameworks perform billions of these update calculations per second on Tensor Cores.',
    hint: 'Multiply α by gradient, then subtract from current w.',
    tags: ['Numerical', 'Parameter Update'],
  },
  {
    id: 'GD-05',
    topic: 'Gradient Descent',
    difficulty: 'hard',
    type: 'formula_id',
    question: 'Which optimization algorithm maintains exponentially decaying averages of both past gradients (m_t) and past squared gradients (v_t)?',
    formula: 'm_t = \\beta_1 m_{t-1} + (1-\\beta_1)g_t, \\quad v_t = \\beta_2 v_{t-1} + (1-\\beta_2)g_t^2',
    options: [
      'Adam (Adaptive Moment Estimation)',
      'Standard SGD',
      'Vanilla Momentum',
      'AdaGrad without RMSProp',
    ],
    correct_answer: 'Adam (Adaptive Moment Estimation)',
    explanation: 'Adam computes bias-corrected first moment (mean) and second moment (uncentered variance) estimates for adaptive per-parameter learning rates.',
    real_time_application: 'Adam and AdamW are the default optimizers for training Transformer architectures like GPT-4 and LLaMA.',
    hint: 'Short for Adaptive Moment Estimation.',
    tags: ['Adam Optimizer', 'Deep Learning'],
  },

  // 4. LOGISTIC REGRESSION
  {
    id: 'LOG-01',
    topic: 'Logistic Regression',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the output range of the Sigmoid activation function σ(z)?',
    formula: '\\sigma(z) = \\frac{1}{1 + e^{-z}}',
    options: [
      '[-1.0, +1.0]',
      '[0.0, 1.0]',
      '[-∞, +∞]',
      '[0.0, +∞]',
    ],
    correct_answer: '[0.0, 1.0]',
    explanation: 'Sigmoid maps any real number z to the open interval (0, 1), allowing predictions to be interpreted as probabilities.',
    real_time_application: 'Spam filters use Sigmoid output to express confidence: e.g. 0.98 probability of spam.',
    hint: 'Probabilities always lie between 0% and 100%.',
    tags: ['Sigmoid', 'Probabilities'],
  },
  {
    id: 'LOG-02',
    topic: 'Logistic Regression',
    difficulty: 'medium',
    type: 'mcq',
    question: 'Why is Binary Cross-Entropy (Log-Loss) used instead of Mean Squared Error for Logistic Regression?',
    formula: 'J(w) = -\\frac{1}{n} \\sum [y_i \\log(\\hat{y}_i) + (1-y_i) \\log(1-\\hat{y}_i)]',
    options: [
      'MSE with Sigmoid produces a non-convex loss function with multiple local minima',
      'Log-loss makes predictions linear',
      'MSE cannot accept floating point values',
      'Log-loss eliminates the need for gradient descent',
    ],
    correct_answer: 'MSE with Sigmoid produces a non-convex loss function with multiple local minima',
    explanation: 'Combining MSE with non-linear Sigmoid creates a non-convex surface where gradient descent gets trapped in local minima. Log-loss guarantees a smooth convex surface.',
    real_time_application: 'Binary classification in ad-click prediction relies on Log-Loss convexity for global optimization convergence.',
    hint: 'Convexity guarantees a single global minimum.',
    tags: ['Log-Loss', 'Convexity'],
  },
  {
    id: 'LOG-03',
    topic: 'Logistic Regression',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'You build a credit card fraud detection model where 99.9% of transactions are legitimate and 0.1% are fraudulent.',
    question: 'Your model predicts 100% of transactions as "Legitimate". What is its accuracy and why is accuracy a bad metric here?',
    options: [
      'Accuracy is 50%; it fails on all positive classes',
      'Accuracy is 99.9%; but it misses 100% of actual fraud cases (Recall is 0%)',
      'Accuracy is 0.1%; it correctly identifies fraud',
      'Accuracy is 100%; the model is optimal',
    ],
    correct_answer: 'Accuracy is 99.9%; but it misses 100% of actual fraud cases (Recall is 0%)',
    explanation: 'On highly imbalanced datasets, a naive model predicting the majority class yields high accuracy (99.9%) while completely failing the task. Precision and Recall/F1 are required.',
    real_time_application: 'Stripe and Visa evaluate fraud models using Precision-Recall Curves (PR-AUC) rather than raw accuracy.',
    hint: 'Consider what happens when positive class instances are extremely rare.',
    tags: ['Metrics', 'Imbalanced Data'],
  },
  {
    id: 'LOG-04',
    topic: 'Logistic Regression',
    difficulty: 'hard',
    type: 'mcq',
    question: 'If z = wx + b evaluates to z = 0, what is the predicted probability σ(z)?',
    formula: '\\sigma(0) = \\frac{1}{1 + e^{0}}',
    options: ['0.0', '0.5', '1.0', '-0.5'],
    correct_answer: '0.5',
    explanation: 'e^0 = 1, so σ(0) = 1 / (1 + 1) = 1/2 = 0.50. This represents the default 50% decision threshold.',
    real_time_application: 'z = 0 defines the hyper-plane linear decision boundary separating class 0 from class 1.',
    hint: 'Any number raised to power 0 equals 1.',
    tags: ['Sigmoid Math', 'Decision Boundary'],
  },

  // 5. DECISION TREES
  {
    id: 'DT-01',
    topic: 'Decision Trees',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which metric measures the impurity of a node in a Decision Tree classification split?',
    options: [
      'Gini Impurity / Information Entropy',
      'Euclidean L2 Distance',
      'Cosine Similarity',
      'Pearson Correlation Coefficient',
    ],
    correct_answer: 'Gini Impurity / Information Entropy',
    explanation: 'Decision Trees split nodes to maximize Information Gain by reducing Gini Impurity or Shannon Entropy.',
    real_time_application: 'Random Forest models in Scikit-Learn default to `criterion="gini"` for split evaluations.',
    hint: 'Measures class randomness or disorder within a node.',
    tags: ['Gini', 'Entropy'],
  },
  {
    id: 'DT-02',
    topic: 'Decision Trees',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'An unpruned Decision Tree is allowed to grow until every leaf node contains exactly 1 training sample.',
    question: 'What performance characteristics will this decision tree display on training vs validation data?',
    options: [
      '100% Training Accuracy, Low Validation Accuracy (Severe Overfitting)',
      '50% Training Accuracy, 100% Validation Accuracy',
      'High Bias on training data, High Generalization',
      'Equal 80% accuracy on both training and validation data',
    ],
    correct_answer: '100% Training Accuracy, Low Validation Accuracy (Severe Overfitting)',
    explanation: 'Fully grown trees memorize every training sample outlier, causing 100% train accuracy but severe failure (overfitting) on unseen test data.',
    real_time_application: 'ML Engineers set `max_depth` or `min_samples_leaf` hyperparameters to prune trees and enforce generalization.',
    hint: 'Growing a tree without depth limits causes memorization.',
    tags: ['Pruning', 'Overfitting'],
  },

  // 6. K-MEANS CLUSTERING
  {
    id: 'KM-01',
    topic: 'K-Means Clustering',
    difficulty: 'easy',
    type: 'mcq',
    question: 'K-Means Clustering belongs to which paradigm of Machine Learning?',
    options: [
      'Supervised Learning',
      'Unsupervised Learning',
      'Reinforcement Learning',
      'Semi-Supervised Label Propagation',
    ],
    correct_answer: 'Unsupervised Learning',
    explanation: 'K-Means clusters unlabeled data points based on feature similarity (Euclidean distance) without target labels.',
    real_time_application: 'Customer segmentation in marketing groups buyers into clusters based on annual spend and visit frequency.',
    hint: 'No target label y is provided during training.',
    tags: ['Clustering', 'Unsupervised'],
  },
  {
    id: 'KM-02',
    topic: 'K-Means Clustering',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'You want to choose the optimal number of clusters (K) for a dataset without ground truth labels.',
    question: 'Which method plots Within-Cluster Sum of Squares (Inertia WCSS) against K to find the point of diminishing returns?',
    options: [
      'Elbow Method',
      'Gradient Descent Descent Curve',
      'ROC Curve',
      'Confusion Matrix Analysis',
    ],
    correct_answer: 'Elbow Method',
    explanation: 'The Elbow Method plots WCSS vs K. The optimal K is selected at the "elbow" bend where adding more clusters yields diminishing reductions in inertia.',
    real_time_application: 'Data scientists use Elbow and Silhouette plots to determine segment counts in market analysis.',
    hint: 'Look for the characteristic elbow bend in the loss curve.',
    tags: ['Elbow Method', 'Inertia'],
  },

  // 7. PCA
  {
    id: 'PCA-01',
    topic: 'PCA',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What is the primary objective of Principal Component Analysis (PCA)?',
    options: [
      'Maximizing the variance of projected data while reducing dimensionality',
      'Minimizing classification loss using Sigmoid boundaries',
      'Increasing dataset feature dimensions to 10,000',
      'Predicting continuous target Y values',
    ],
    correct_answer: 'Maximizing the variance of projected data while reducing dimensionality',
    explanation: 'PCA projects high-dimensional data onto orthogonal principal components that capture maximum variance while dropping low-information dimensions.',
    real_time_application: 'Facial recognition systems (Eigenfaces) use PCA to compress 1024x1024 image pixels down to 50 key feature vectors.',
    hint: 'Focuses on variance preservation across orthogonal axes.',
    tags: ['Dimensionality Reduction', 'PCA'],
  },

  // 8. NEURAL NETWORKS
  {
    id: 'NN-01',
    topic: 'Neural Networks',
    difficulty: 'easy',
    type: 'mcq',
    question: 'Which activation function is most widely used in hidden layers of modern deep neural networks to prevent vanishing gradients for positive inputs?',
    formula: 'f(x) = \\max(0, x)',
    options: [
      'ReLU (Rectified Linear Unit)',
      'Sigmoid',
      'Tanh (Hyperbolic Tangent)',
      'Linear Identity',
    ],
    correct_answer: 'ReLU (Rectified Linear Unit)',
    explanation: 'ReLU f(x) = max(0, x) has derivative 1 for x > 0, preventing vanishing gradients and training significantly faster than Sigmoid.',
    real_time_application: 'Convolutional neural networks (CNNs) in self-driving cars use ReLU activation across millions of hidden neurons.',
    hint: 'Outputs 0 for negative values and x for positive values.',
    tags: ['ReLU', 'Activations'],
  },
  {
    id: 'NN-02',
    topic: 'Neural Networks',
    difficulty: 'medium',
    type: 'mcq',
    question: 'What algorithm computes parameter gradients across hidden layers using the Calculus Chain Rule during neural network training?',
    options: [
      'Backpropagation',
      'Forward Propagation',
      'K-Means Initialization',
      'Heuristic Search',
    ],
    correct_answer: 'Backpropagation',
    explanation: 'Backpropagation applies the chain rule backward from the output layer loss to compute partial derivatives ∂J/∂w for every weight in the network.',
    real_time_application: 'PyTorch Autograd engine executes backpropagation automatically on every loss.backward() call.',
    hint: 'Propagates error backward from output to input.',
    tags: ['Backpropagation', 'Chain Rule'],
  },
  {
    id: 'NN-03',
    topic: 'Neural Networks',
    difficulty: 'hard',
    type: 'scenario',
    context_or_scenario: 'During training of a 50-layer deep neural network with Sigmoid hidden activations, initial layer weights stop updating completely.',
    question: 'What classic deep learning problem is occurring and how can it be fixed?',
    options: [
      'Vanishing Gradient Problem; replace Sigmoid with ReLU activation and use He/Xavier initialization',
      'Exploding Gradient Problem; increase learning rate by 10x',
      'Underfitting; decrease hidden layer count',
      'Dead ReLU Problem; switch to pure Sigmoid activations',
    ],
    correct_answer: 'Vanishing Gradient Problem; replace Sigmoid with ReLU activation and use He/Xavier initialization',
    explanation: 'Sigmoid derivatives max out at 0.25. Multiplying 50 fractional derivatives together reduces gradients to near zero in early layers. ReLU solves this.',
    real_time_application: 'ResNet skip connections and ReLU activation allowed deep learning to scale to 152+ layer networks without vanishing gradients.',
    hint: 'Repeated multiplication of small decimals (< 1) causes gradients to vanish.',
    tags: ['Vanishing Gradient', 'Deep Learning'],
  },

  // 9. OVERFITTING & UNDERFITTING
  {
    id: 'OF-01',
    topic: 'Overfitting',
    difficulty: 'easy',
    type: 'mcq',
    question: 'What does High Bias indicate about a Machine Learning model?',
    options: [
      'The model is underfitting because it is too simple to capture underlying patterns',
      'The model is severe overfitting by memorizing noisy training points',
      'The model has perfect 100% test accuracy',
      'The model dataset contains zero features',
    ],
    correct_answer: 'The model is underfitting because it is too simple to capture underlying patterns',
    explanation: 'High Bias occurs when model capacity is too low (underfitting), causing high error on both training and test sets.',
    real_time_application: 'Trying to fit complex housing market trends with a single straight line produces high bias.',
    hint: 'High bias = simplistic model assumptions.',
    tags: ['High Bias', 'Underfitting'],
  },
  {
    id: 'OF-02',
    topic: 'Overfitting',
    difficulty: 'medium',
    type: 'scenario',
    context_or_scenario: 'During training, training loss continues dropping toward 0.01 while validation loss begins curving upward after epoch 20.',
    question: 'What action should be taken to prevent overfitting at epoch 20?',
    options: [
      'Apply Early Stopping to halt training at epoch 20',
      'Increase epochs from 20 to 500',
      'Remove regularization penalties',
      'Increase model layer count',
    ],
    correct_answer: 'Apply Early Stopping to halt training at epoch 20',
    explanation: 'When validation loss begins rising while train loss falls, the model is memorizing noise. Early stopping halts training at minimum validation loss.',
    real_time_application: 'Keras and PyTorch Lightning use EarlyStopping callbacks to save check-pointed weights at peak validation performance.',
    hint: 'Stop training when validation performance starts degrading.',
    tags: ['Early Stopping', 'Validation'],
  },

  // 10. CUMULATIVE MASTER CASE STUDY
  {
    id: 'FINAL-01',
    topic: 'Cumulative Case Study',
    difficulty: 'easy',
    type: 'case_study',
    context_or_scenario: 'Case Study: Real Estate Price Predictor\nAn e-commerce real estate portal trains a model to predict house sales. The dataset contains 50 features with severe multicollinearity and noisy outliers.',
    question: 'Which regularized model approach best reduces feature collinearity while maintaining interpretable predictions?',
    options: [
      'Ridge Regression (L2) or Lasso (L1) to penalize correlated feature weights',
      'Unpruned Decision Tree with infinite depth',
      'Vanilla K-Means Clustering without target features',
      'Single Neuron Perceptron without activation',
    ],
    correct_answer: 'Ridge Regression (L2) or Lasso (L1) to penalize correlated feature weights',
    explanation: 'L1/L2 regularization handles multicollinearity by shrinking parameter magnitudes and preventing inflated variance.',
    real_time_application: 'Real estate pricing engines apply Ridge regularization to stabilize coefficient estimates across correlated features like square feet and room count.',
    hint: 'Regularization controls model variance when features are correlated.',
    tags: ['Case Study', 'Real Estate'],
  },
  {
    id: 'FINAL-02',
    topic: 'Cumulative Case Study',
    difficulty: 'medium',
    type: 'case_study',
    context_or_scenario: 'Case Study: Autonomous Vehicle Obstacle Classifier\nAn autonomous driving team builds an obstacle classification network. Training loss oscillates violently between 0.2 and 4.5 without converging.',
    question: 'Which pair of hyperparameter fixes will stabilize gradient descent updates?',
    options: [
      'Reduce learning rate α and apply Adam optimizer with momentum',
      'Increase learning rate by 100x and remove normalization',
      'Remove hidden layers and use pure MSE loss',
      'Switch to unnormalized Stochastic Gradient Descent with α = 5.0',
    ],
    correct_answer: 'Reduce learning rate α and apply Adam optimizer with momentum',
    explanation: 'Violent loss oscillations stem from excessive learning rate overshooting gradient valleys. Reducing α and utilizing Adam momentum restores steady convergence.',
    real_time_application: 'Tesla Autopilot vision networks utilize AdamW optimizer with cosine learning rate decay schedules.',
    hint: 'Oscillations occur when step size is too large for local curvature.',
    tags: ['Case Study', 'Autonomous Driving'],
  },
  {
    id: 'FINAL-03',
    topic: 'Cumulative Case Study',
    difficulty: 'hard',
    type: 'case_study',
    context_or_scenario: 'Case Study: Medical Disease Screening Pipeline\nA hospital deploys an AI screening model for rare lung cancer detection (prevalence: 0.5%). The baseline model achieves 99.5% accuracy but fails on 80% of true cancer cases.',
    question: 'How should the engineering team modify the loss function and evaluation strategy?',
    options: [
      'Use Weighted Focal Cross-Entropy Loss to heavily penalize false negatives, and evaluate using Recall and F1-Score',
      'Keep standard MSE Loss and evaluate using accuracy alone',
      'Train K-Means clustering with K=2 and ignore predictions',
      'Remove validation splits and double the dataset noise',
    ],
    correct_answer: 'Use Weighted Focal Cross-Entropy Loss to heavily penalize false negatives, and evaluate using Recall and F1-Score',
    explanation: 'In medical screening, missing a positive case (false negative) is catastrophic. Class-weighted loss and Recall optimization ensure high detection sensitivity.',
    real_time_application: 'Hospital AI systems mandate high Recall (> 95%) to ensure no high-risk cancer scans are missed by radiologists.',
    hint: 'Prioritize minimizing False Negatives in medical diagnostics.',
    tags: ['Case Study', 'Medical AI'],
  },
];
